//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceSystem.Resources.Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceFinanceWeb {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceFinanceWeb() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FinanceSystem.Resources.Web.ResourceFinanceWeb", typeof(ResourceFinanceWeb).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed.
        /// </summary>
        public static string Error_AuthenticationFailed {
            get {
                return ResourceManager.GetString("Error_AuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error canceling {0}: {1}.
        /// </summary>
        public static string Error_CancelEntity {
            get {
                return ResourceManager.GetString("Error_CancelEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete system {0}..
        /// </summary>
        public static string Error_CannotDeleteSystemEntity {
            get {
                return ResourceManager.GetString("Error_CannotDeleteSystemEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot edit system {0}..
        /// </summary>
        public static string Error_CannotEditSystemEntity {
            get {
                return ResourceManager.GetString("Error_CannotEditSystemEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating {0}: {1}.
        /// </summary>
        public static string Error_Creating {
            get {
                return ResourceManager.GetString("Error_Creating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit card is required for this payment method..
        /// </summary>
        public static string Error_CreditCardRequired {
            get {
                return ResourceManager.GetString("Error_CreditCardRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting {0}: {1}.
        /// </summary>
        public static string Error_Deleting {
            get {
                return ResourceManager.GetString("Error_Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error generating {0}: {1}.
        /// </summary>
        public static string Error_Generating {
            get {
                return ResourceManager.GetString("Error_Generating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to generate identity.
        /// </summary>
        public static string Error_IdentityGeneration {
            get {
                return ResourceManager.GetString("Error_IdentityGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token.
        /// </summary>
        public static string Error_InvalidToken {
            get {
                return ResourceManager.GetString("Error_InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading {0}: {1}.
        /// </summary>
        public static string Error_Loading {
            get {
                return ResourceManager.GetString("Error_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error logging out: {0}.
        /// </summary>
        public static string Error_Logout {
            get {
                return ResourceManager.GetString("Error_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error marking {0} as {1}: {2}.
        /// </summary>
        public static string Error_MarkStatus {
            get {
                return ResourceManager.GetString("Error_MarkStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not identify the {0} related to this installment..
        /// </summary>
        public static string Error_ParentEntityNotFound {
            get {
                return ResourceManager.GetString("Error_ParentEntityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to edit other users, only your own..
        /// </summary>
        public static string Error_PermissionDenied {
            get {
                return ResourceManager.GetString("Error_PermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error preparing form: {0}.
        /// </summary>
        public static string Error_PreparingForm {
            get {
                return ResourceManager.GetString("Error_PreparingForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error refreshing price: {0}.
        /// </summary>
        public static string Error_RefreshingPrice {
            get {
                return ResourceManager.GetString("Error_RefreshingPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating {0}: {1}.
        /// </summary>
        public static string Error_Updating {
            get {
                return ResourceManager.GetString("Error_Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} canceled successfully!.
        /// </summary>
        public static string Success_Canceled {
            get {
                return ResourceManager.GetString("Success_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} created successfully!.
        /// </summary>
        public static string Success_Created {
            get {
                return ResourceManager.GetString("Success_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deleted successfully!.
        /// </summary>
        public static string Success_Deleted {
            get {
                return ResourceManager.GetString("Success_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login successful!.
        /// </summary>
        public static string Success_Login {
            get {
                return ResourceManager.GetString("Success_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} marked as {1} successfully!.
        /// </summary>
        public static string Success_StatusChanged {
            get {
                return ResourceManager.GetString("Success_StatusChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} updated successfully!.
        /// </summary>
        public static string Success_Updated {
            get {
                return ResourceManager.GetString("Success_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email is required..
        /// </summary>
        public static string Validation_EmailRequired {
            get {
                return ResourceManager.GetString("Validation_EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select at least one role..
        /// </summary>
        public static string Validation_SelectRole {
            get {
                return ResourceManager.GetString("Validation_SelectRole", resourceCulture);
            }
        }
    }
}
