//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceSystem.Resources.Web {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceFinanceWeb {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceFinanceWeb() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FinanceSystem.Resources.Web.ResourceFinanceWeb", typeof(ResourceFinanceWeb).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Authentication failed.
        /// </summary>
        public static string Error_AuthenticationFailed {
            get {
                return ResourceManager.GetString("Error_AuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error canceling {0}: {1}.
        /// </summary>
        public static string Error_CancelEntity {
            get {
                return ResourceManager.GetString("Error_CancelEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cannot delete system {0}..
        /// </summary>
        public static string Error_CannotDeleteSystemEntity {
            get {
                return ResourceManager.GetString("Error_CannotDeleteSystemEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cannot edit system {0}..
        /// </summary>
        public static string Error_CannotEditSystemEntity {
            get {
                return ResourceManager.GetString("Error_CannotEditSystemEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error creating {0}: {1}.
        /// </summary>
        public static string Error_Creating {
            get {
                return ResourceManager.GetString("Error_Creating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Credit card is required for this payment method..
        /// </summary>
        public static string Error_CreditCardRequired {
            get {
                return ResourceManager.GetString("Error_CreditCardRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error deleting {0}: {1}.
        /// </summary>
        public static string Error_Deleting {
            get {
                return ResourceManager.GetString("Error_Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error generating {0}: {1}.
        /// </summary>
        public static string Error_Generating {
            get {
                return ResourceManager.GetString("Error_Generating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Failed to generate identity.
        /// </summary>
        public static string Error_IdentityGeneration {
            get {
                return ResourceManager.GetString("Error_IdentityGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid token.
        /// </summary>
        public static string Error_InvalidToken {
            get {
                return ResourceManager.GetString("Error_InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error loading {0}: {1}.
        /// </summary>
        public static string Error_Loading {
            get {
                return ResourceManager.GetString("Error_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error logging out: {0}.
        /// </summary>
        public static string Error_Logout {
            get {
                return ResourceManager.GetString("Error_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error marking {0} as {1}: {2}.
        /// </summary>
        public static string Error_MarkStatus {
            get {
                return ResourceManager.GetString("Error_MarkStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Could not identify the {0} related to this installment..
        /// </summary>
        public static string Error_ParentEntityNotFound {
            get {
                return ResourceManager.GetString("Error_ParentEntityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a You do not have permission to edit other users, only your own..
        /// </summary>
        public static string Error_PermissionDenied {
            get {
                return ResourceManager.GetString("Error_PermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error preparing form: {0}.
        /// </summary>
        public static string Error_PreparingForm {
            get {
                return ResourceManager.GetString("Error_PreparingForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error refreshing price: {0}.
        /// </summary>
        public static string Error_RefreshingPrice {
            get {
                return ResourceManager.GetString("Error_RefreshingPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error updating {0}: {1}.
        /// </summary>
        public static string Error_Updating {
            get {
                return ResourceManager.GetString("Error_Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} canceled successfully!.
        /// </summary>
        public static string Success_Canceled {
            get {
                return ResourceManager.GetString("Success_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} created successfully!.
        /// </summary>
        public static string Success_Created {
            get {
                return ResourceManager.GetString("Success_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} deleted successfully!.
        /// </summary>
        public static string Success_Deleted {
            get {
                return ResourceManager.GetString("Success_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} marked as {1} successfully!.
        /// </summary>
        public static string Success_StatusChanged {
            get {
                return ResourceManager.GetString("Success_StatusChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} updated successfully!.
        /// </summary>
        public static string Success_Updated {
            get {
                return ResourceManager.GetString("Success_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a An email is required..
        /// </summary>
        public static string Validation_EmailRequired {
            get {
                return ResourceManager.GetString("Validation_EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a You must select at least one role..
        /// </summary>
        public static string Validation_SelectRole {
            get {
                return ResourceManager.GetString("Validation_SelectRole", resourceCulture);
            }
        }
    }
}
